### ISSUE TITLE
Improve AO baking

### ISSUE THREAD

**Issue by nashmuhandes** [ZDoom/ZDRay#24]
Image 1: the darkening seems to be too abrupt despite the distance between each wall surface being quite far
Image 2: there seems to be some bright glow as a result of the AO (?)

![Screenshot_Disdain_20220216_000534](https://user-images.githubusercontent.com/4926156/154101231-1d4bee6c-88b7-4975-9565-a3048244d7b4.png)

![Screenshot_Disdain_20220216_000549](https://user-images.githubusercontent.com/4926156/154101250-b3480180-9ee6-4f41-b535-269c3c835f61.png)

**Comment by dpjudas** [comment]
This should be fixed now.
